# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('course_num', models.CharField(max_length=10)),
                ('instructors', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=500)),
                ('asTaughtIn', models.CharField(max_length=500)),
                ('syllabus', models.CharField(max_length=20000)),
                ('readings', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.CourseDiscipline')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.CourseDiscipline'),
        ),
    ]
