# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180712_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
