# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tools',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
