# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_course_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
