# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-25 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180724_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
